Alternative approach for case support
xcompact3d/x3d2 pull request #128
Opened 2024-10-09 10:15 UTC by semi-h

#121 implements a new class that contains solver, and allows users to extend this new class for any custom case.

In this PR I tried a similar approach by extending the `solver` class directly. Functionality is similar, and I think this is a bit more clear. For a custom case users will be able to write a custom forcing, BC, or postprocessing functions in a dedicated file/module.

2025-01-09 12:17 UTC, semi-h commented
I ended up changing the approach back to having a `base_case` and its extentions instead of handling different cases by extending `solver`. 

This is because I realised that in some flow cases we would need to extend the `solver` in a similar way and this would require code duplication. For example, if two distinct flow cases require temperature field (or maybe just a scalar field), the strategy based on `solver` extentions would require us to edit transeq in a similar way in two different flow case modules. But with a `base_case` extentions we can have the scalar extention only once as a new solver and then the two different flow cases can use this new solver, minimising the duplications.

Also, this allowed `solver_t` to be more abstract, only defining the transport equation and pressure correction related subroutines. Stuff related to flow cases such as boundary conditions, source term additions, and postprocessing is defined in `base_class` and overwritten in its extensions if necessary. I've been using this structure in parallel in the Channel case #136 and it works quite well. With this structure its now trivial to add a new flow case and work on it in isolation.

2025-01-09 13:48 UTC, pbartholomew08 requested changes
This all looks good and I think will allow flexibility to create new cases fairly easily. I would only suggest addition of a few comments.

2025-01-13 14:59 UTC, Nanoseb reviewed
just a couple of small comments, otherwise it looks good

2025-01-13 16:09 UTC, semi-h commented on src/case/base_case.f90
> +    subroutine postprocess(self, t)
Passing the iteration number now, also printing alongside t

2025-01-13 16:11 UTC, semi-h commented on src/case/tgv.f90
> +  subroutine initial_conditions_tgv(self)
Moved the main loop up to base_case. The new `set_init` in base_case inputs a pure function and a field, then sets the field. This way later on we can have for example a Temperature field set by a case easily.

2025-01-14 09:16 UTC, Nanoseb commented on src/case/tgv.f90
> +  subroutine initial_conditions_tgv(self)
good idea indeed. The best of both worlds

2025-01-14 11:45 UTC, merged