Channel case
xcompact3d/x3d2 pull request #136
Opened 2024-12-20 19:46 UTC by semi-h

Based off the case support branch for the moment.

Adds 010 BC support to FFT based Poisson solver to enable a channel case configuration.

2025-02-19 20:42 UTC, pbartholomew08 commented on src/case/channel.f90
> +    call self%solver%host_allocator%release_block(u_host)
It's essentially doing a volume average (I think) this - or the volume integral - would seem like a reasonable backend kernel to have as it will arise in other cases too.

2025-02-20 08:41 UTC, slaizet commented on src/case/channel.f90
> +    call self%solver%host_allocator%release_block(u_host)
agreed that we will this volume average for various cases so definitely worth investigating a solution on GPU. What do you have in mind @semi-h ? We can discuss about it on Monday during our weekly meeting.

2025-02-20 08:47 UTC, semi-h commented on src/case/channel.f90
> +    call self%solver%host_allocator%release_block(u_host)
If that's the case I'm happy to add a backend function for this operation, thanks! It'll be a simple summation kernel for now but with stretching I'll have to update it slightly, possibly accounting for stretching in all three directions.

2025-02-20 08:55 UTC, semi-h commented on src/case/channel.f90
> +    call self%solver%host_allocator%release_block(u_host)
By the way, both GPU and CPU kernels for this operation is trivial, very similar to stuff I already did in #153.

2025-03-03 12:51 UTC, semi-h commented on src/case/channel.f90
> +    call self%solver%host_allocator%release_block(u_host)
All done

2025-03-03 17:23 UTC, pbartholomew08 requested changes
It would be good to clarify the new field/face subroutine.

2025-03-03 17:23 UTC, pbartholomew08 commented on src/backend.f90
> +      !! Set a face in field
I can't figure out from the commen what this should be doing

2025-03-14 11:04 UTC, semi-h commented on src/backend.f90
> +      !! Set a face in field
Updated this bit with a detailed description

2025-03-14 14:03 UTC, merged